import { emptyTopicAnalysis } from './labels'
import type { NewsItem, Thesis, Topic } from './types'

export const demoNews: NewsItem[] = [
  {
    id: 'news-dataflow',
    url: 'https://example.com/dataflow-harness',
    title: 'DataFlow-Harness turns agent reliability into an engineering discipline',
    source: 'Research signal',
    summary:
      'A structured harness combines evaluations, traces, and recovery paths so teams can improve agents without treating every failure as a one-off.',
    takeaway:
      'Reliability work is moving from model quality to repeatable agent engineering.',
    industryImportance:
      'Agent reliability is becoming a distinct engineering layer, not a model-quality afterthought.',
    qiraRelevance:
      'QIRA should treat harness quality as part of the product surface, not only backend evals.',
    teamSynthesis:
      'Team input suggests reliability will be judged by recovery paths, not just accuracy. Several inputs point to traces as the shared language.',
    discussionPriorityScore: 24,
    category: 'ai_capability',
    sourceType: 'captured_news',
    capturedAt: '2026-07-29T10:00:00Z',
    capturedBy: 'Ziyan',
    editorialStatus: 'processed',
    ideaCount: 2,
    discussionStatus: 'not_discussed',
    voteCount: 2,
    updatedAt: '2026-08-22T09:00:00Z',
    topicLinks: [
      {
        topicId: 'topic-harness',
        topicTitle: 'Harness engineering',
        monthLabel: 'November 2026',
      },
    ],
  },
  {
    id: 'news-granola',
    url: 'https://example.com/granola-watch',
    title: 'Granola brings ambient meeting memory to Apple Watch',
    source: 'Product signal',
    summary:
      'The watch becomes a lightweight capture surface, shifting assistant interaction from deliberate prompting toward ambient context collection.',
    takeaway:
      'Wearables may become a primary AI entry point rather than a companion screen.',
    industryImportance:
      'Ambient capture is moving assistants from explicit prompts toward always-available context.',
    qiraRelevance:
      'QIRA should watch consent cues and review surfaces as capture becomes wearable.',
    teamSynthesis: '',
    discussionPriorityScore: 12,
    category: 'ai_hardware',
    sourceType: 'captured_news',
    capturedAt: '2026-07-30T11:30:00Z',
    updatedAt: '2026-08-21T10:00:00Z',
    capturedBy: 'Nicole',
    editorialStatus: 'processed',
    ideaCount: 1,
    discussionStatus: 'not_discussed',
    voteCount: 1,
    topicLinks: [],
  },
  {
    id: 'news-pocket',
    url: 'https://techcrunch.com/example-pocket',
    title: 'Meta quietly launches vibe-coded gaming app Pocket',
    source: 'TechCrunch',
    summary:
      'A team capture waiting for editorial review. It may support a broader thesis about software creation becoming an interaction primitive.',
    takeaway: '',
    industryImportance: '',
    qiraRelevance: '',
    teamSynthesis: '',
    discussionPriorityScore: 2,
    category: 'ai_software',
    sourceType: 'captured_news',
    capturedAt: '2026-08-03T03:00:00Z',
    updatedAt: '2026-08-03T03:00:00Z',
    capturedBy: 'Team',
    editorialStatus: 'pending',
    ideaCount: 0,
    discussionStatus: 'not_discussed',
    voteCount: 0,
    topicLinks: [],
  },
  {
    id: 'news-browser-agent',
    url: 'https://example.com/browser-agent-entry',
    title: 'Browser agents turn the address bar into an invocation layer',
    source: 'Industry signal',
    summary:
      'New assistant entry points sit beside search, making invocation a product surface rather than a chat destination.',
    takeaway: 'Entry points are becoming a competitive layer across browsers and OS shells.',
    industryImportance: 'Whoever owns invocation owns the first step of work.',
    qiraRelevance: 'QIRA should treat browser/OS entry as a first-class interaction surface.',
    teamSynthesis: '',
    discussionPriorityScore: 18,
    category: 'interaction',
    sourceType: 'captured_news',
    capturedAt: '2026-08-26T09:00:00Z',
    updatedAt: '2026-08-27T14:00:00Z',
    capturedBy: 'Team',
    editorialStatus: 'processed',
    discussedAt: '2026-08-28T10:00:00Z',
    ideaCount: 0,
    discussionStatus: 'discussed',
    voteCount: 4,
    votedByMe: true,
    topicLinks: [],
  },
  {
    id: 'news-platform-runtime',
    url: 'https://example.com/agent-runtime',
    title: 'Platform vendors ship a shared agent runtime for partners',
    source: 'Ecosystem signal',
    summary:
      'A common runtime lets third parties plug tools into one permission and memory model.',
    takeaway: 'Ecosystem lock-in is shifting from models to runtime and permissions.',
    industryImportance: 'Runtimes may matter more than any single model release.',
    qiraRelevance: 'QIRA should track where partner tools attach: model, runtime, or OS.',
    teamSynthesis: 'Several inputs point to permissions as the real switching cost.',
    discussionPriorityScore: 16,
    category: 'ecosystem',
    sourceType: 'captured_news',
    capturedAt: '2026-08-25T08:00:00Z',
    updatedAt: '2026-08-26T11:00:00Z',
    capturedBy: 'Team',
    editorialStatus: 'processed',
    ideaCount: 0,
    discussionStatus: 'not_discussed',
    voteCount: 3,
    topicLinks: [],
  },
  {
    id: 'news-earnings-ai',
    url: 'https://example.com/ai-earnings',
    title: 'Earnings calls treat AI attach rate as a core KPI',
    source: 'Market signal',
    summary:
      'Multiple vendors now report AI feature attach next to seats and consumption.',
    takeaway: 'AI is being measured as product attach, not research spend.',
    industryImportance: 'Board-level metrics will force clearer AI product packaging.',
    qiraRelevance: 'QIRA narrative should connect capability work to attach and usage.',
    teamSynthesis: '',
    discussionPriorityScore: 9,
    category: 'industry_events',
    sourceType: 'captured_news',
    capturedAt: '2026-08-24T16:00:00Z',
    updatedAt: '2026-08-24T16:00:00Z',
    capturedBy: 'Team',
    editorialStatus: 'processed',
    ideaCount: 0,
    discussionStatus: 'not_discussed',
    voteCount: 1,
    topicLinks: [],
  },
]

export const demoTopics: Topic[] = [
  {
    id: 'topic-harness',
    title: 'Harness engineering',
    thesisId: 'thesis-agent-systems',
    monthKey: '2026-11',
    monthLabel: 'November 2026',
    category: 'ai_capability',
    status: 'scheduled',
    threadStatus: 'open',
    kind: 'insight',
    notes: 'From model quality to repeatable system reliability.',
    analysis: {
      ...emptyTopicAnalysis,
      keyQuestion: 'Can harnesses become a productized reliability layer?',
    },
    outputs: [],
    ownerId: 'demo-user',
    ownerName: 'Ziyan',
    decisionSummary: '',
    nextStep: 'Define the minimum harness evaluation set.',
    outcomeUrl: '',
    createdAt: '2026-07-20T09:00:00Z',
    displayOrder: 1,
    supportingNews: ['news-dataflow'],
  },
  {
    id: 'topic-ambient',
    title: 'Ambient capture surfaces',
    thesisId: 'thesis-human-ai',
    monthKey: '2026-10',
    monthLabel: 'October 2026',
    category: 'interaction',
    status: 'researching',
    threadStatus: 'in_progress',
    kind: 'poc',
    notes: 'How wearables reshape memory, consent, and assistant context.',
    analysis: { ...emptyTopicAnalysis },
    outputs: [],
    ownerId: 'demo-user',
    ownerName: 'Nicole',
    decisionSummary: '',
    nextStep: 'Prototype consent and review cues.',
    outcomeUrl: '',
    createdAt: '2026-07-22T09:00:00Z',
    displayOrder: 1,
    supportingNews: [],
  },
  {
    id: 'topic-genui',
    title: 'Generative UI as software',
    thesisId: 'thesis-agent-systems',
    parentTopicId: 'topic-harness',
    monthKey: '2026-12',
    monthLabel: 'December 2026',
    category: 'ai_software',
    status: 'idea',
    threadStatus: 'open',
    kind: 'roadmap',
    notes: 'Interfaces assembled at intent time need new evaluation methods.',
    analysis: { ...emptyTopicAnalysis },
    outputs: [],
    decisionSummary: '',
    nextStep: '',
    outcomeUrl: '',
    createdAt: '2026-07-24T09:00:00Z',
    displayOrder: 1,
    supportingNews: [],
  },
  {
    id: 'topic-pool-idea',
    title: 'On-device agent privacy tradeoffs',
    monthKey: '',
    monthLabel: 'Unscheduled',
    category: 'ecosystem',
    status: 'idea',
    threadStatus: 'parked',
    kind: 'pov',
    notes: 'Parked until a launch window or industry event makes timing clear.',
    analysis: { ...emptyTopicAnalysis },
    outputs: [],
    decisionSummary: '',
    nextStep: '',
    outcomeUrl: '',
    createdAt: '2026-08-01T09:00:00Z',
    displayOrder: 1,
    supportingNews: ['news-granola'],
  },
]

export const demoTheses: Thesis[] = [
  {
    id: 'thesis-agent-systems',
    title: 'Agent systems become a new software layer',
    description:
      'A long-range portfolio connecting harnesses, generative interfaces, and autonomous action.',
    horizon: '2026–2027',
    topicIds: ['topic-harness', 'topic-genui'],
  },
  {
    id: 'thesis-human-ai',
    title: 'Human–AI interaction moves into the environment',
    description:
      'Persistent context and ambient devices change when and how people invoke intelligence.',
    horizon: '2026–2027',
    topicIds: ['topic-ambient'],
  },
]
